version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet-test-tooling:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.collector"
          - "xunit*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

